spring:
  datasource:
    url: jdbc:mysql://localhost:3306/android
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
